15:4: not a valid test operator:  
15:4: not a valid test operator: 12.4
21:4: not a valid test operator: (
21:4: not a valid test operator: 535.129.03
15:4: not a valid test operator:  
15:4: not a valid test operator: 12.4
21:4: not a valid test operator: (
21:4: not a valid test operator: 535.129.03
15:4: not a valid test operator:  
15:4: not a valid test operator: 12.4
21:4: not a valid test operator: (
21:4: not a valid test operator: 535.129.03
15:4: not a valid test operator:  
15:4: not a valid test operator: 12.4
21:4: not a valid test operator: (
21:4: not a valid test operator: 535.129.03
[rank3]: Traceback (most recent call last):
[rank3]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 152, in <module>
[rank3]:     main()
[rank3]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 77, in main
[rank3]:     model.to(dist_util.dev())
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1152, in to
[rank3]:     return self._apply(convert)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 825, in _apply
[rank3]:     param_applied = fn(param)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1150, in convert
[rank3]:     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
[rank3]: RuntimeError: CUDA error: invalid device ordinal
[rank3]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank3]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank3]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 152, in <module>
[rank1]:     main()
[rank1]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 77, in main
[rank1]:     model.to(dist_util.dev())
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1152, in to
[rank1]:     return self._apply(convert)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 825, in _apply
[rank1]:     param_applied = fn(param)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1150, in convert
[rank1]:     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
[rank1]: RuntimeError: CUDA error: invalid device ordinal
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank2]: Traceback (most recent call last):
[rank2]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 152, in <module>
[rank2]:     main()
[rank2]:   File "/oscar/home/xwang259/CSCI1430-Final-Project-MedImage-Segmentation/segdiff/image_train_diff_vaih.py", line 77, in main
[rank2]:     model.to(dist_util.dev())
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1152, in to
[rank2]:     return self._apply(convert)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank2]:     module._apply(fn)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 802, in _apply
[rank2]:     module._apply(fn)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 825, in _apply
[rank2]:     param_applied = fn(param)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1150, in convert
[rank2]:     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
[rank2]: RuntimeError: CUDA error: invalid device ordinal
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

srun: Job 1985357 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Job 1985357 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Job 1985357 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: error: Unable to create step for job 1985357: Job/step already completing or completed
srun: error: Unable to create step for job 1985357: Job/step already completing or completed
srun: Job step aborted: Waiting up to 182 seconds for job step to finish.
srun: error: Unable to create step for job 1985357: Job/step already completing or completed
slurmstepd: error: *** JOB 1985357 ON gpu2114 CANCELLED AT 2024-05-10T15:08:08 ***
